name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make clang

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'    

    - name: Build
      run: make all

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install make

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'    

    - name: Build
      run: make all

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: choco install make mingw

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'    

    - name: Build
      shell: bash
      run: make all