name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && apt-get install -y make clang

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'    

    - name: Buil
      run: make all
